version: '3.9'
services:
    backend:
      build: ./backend
      container_name: 'backend'
      env_file:
        - ./backend/.env
      ports:
        - '8000:8000'
    frontend:
      build: ./frontend
      container_name: 'frontend'
      env_file:
        - ./frontend/.env
      ports:
        - '5173:5173'
      depends_on:
        - backend